import {render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {it,expect,vi} from 'vitest';
import {SessionContext} from '../session/sessionContext.js';
import {CorrectionReversalControls} from './CorrectionReversalControls.jsx';
const leagueId='11111111-1111-4111-8111-111111111111',correctionId='22222222-2222-4222-8222-222222222222';
const preview={leagueId,correctionId,feature:'roster',playerName:'Casey Skater',current:{teamId:'team',rosterCategory:'Bench',positionGroup:'F',slotNumber:1},restore:{teamId:'team',rosterCategory:'Active',positionGroup:'F',slotNumber:2},warnings:[{code:'TEAM_ROSTER_INCOMPLETE',teamId:'team'}],teamNames:[{id:'team',name:'Ice Owls'}],previewHash:'a'.repeat(64)};
function setup(fail=false){let attempts=0;const request=vi.fn(async(url,o)=>{if(url.endsWith('/apply')&&fail&&++attempts===1)throw Error('network');const data=url.endsWith('/apply')?{leagueId,correctionId}:url.endsWith('/preview')?preview:{leagueId,corrections:[{id:correctionId,feature:'roster',playerName:'Casey Skater',at:0,reason:'Moved to bench',reversed:0}]};if(o.validateData(data)!==true)throw Error('Invalid');return {data};});render(<SessionContext.Provider value={{httpClient:{request}}}><CorrectionReversalControls leagueId={leagueId}/></SessionContext.Provider>);return {request,user:userEvent.setup()};}
it('shows before and after values and warnings before a deliberate reversal',async()=>{const {request,user}=setup();expect(request).not.toHaveBeenCalled();await user.click(screen.getByText('Reverse an administrative correction'));await user.selectOptions(await screen.findByLabelText('Previous correction'),correctionId);await user.type(screen.getByLabelText('Reason for reversal'),'Undo mistaken move');await user.click(screen.getByRole('button',{name:'Preview reversal'}));await screen.findByText('Restore Casey Skater');expect(screen.getByText('Bench')).toBeInTheDocument();expect(screen.getByText('Active')).toBeInTheDocument();expect(screen.getByText(/team roster incomplete/)).toBeInTheDocument();expect(request.mock.calls.filter(([url])=>url.endsWith('/apply'))).toHaveLength(0);await user.click(screen.getByRole('button',{name:'Confirm reversal'}));await screen.findByText('Correction reversed. Original history retained.');});
it('retries uncertain confirmation using the same key and body',async()=>{const {request,user}=setup(true);await user.click(screen.getByText('Reverse an administrative correction'));await user.selectOptions(await screen.findByLabelText('Previous correction'),correctionId);await user.type(screen.getByLabelText('Reason for reversal'),'Undo mistaken move');await user.click(screen.getByRole('button',{name:'Preview reversal'}));await user.click(await screen.findByRole('button',{name:'Confirm reversal'}));await screen.findByRole('alert');expect(screen.getByLabelText('Reason for reversal')).toBeDisabled();await user.click(screen.getByRole('button',{name:'Confirm reversal'}));await screen.findByText('Correction reversed. Original history retained.');const calls=request.mock.calls.filter(([url])=>url.endsWith('/apply'));expect(calls[0][1].idempotencyKey).toBe(calls[1][1].idempotencyKey);expect(calls[0][1].body).toEqual(calls[1][1].body);});
