import {render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {it,expect,vi} from 'vitest';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {SessionContext} from '../session/sessionContext.js';
import {GuidedLeagueResetControls} from './GuidedLeagueResetControls.jsx';
const leagueId='11111111-1111-4111-8111-111111111111',archiveId='22222222-2222-4222-8222-222222222222';
const manifest={leagueName:'Test League',clear:[{label:'Candidate Cards',count:4},{label:'Auctions',count:12}],preserved:['Manager accounts and team access','Other leagues'],preparation:'Choose new dates before starting.',recovery:'Later manager work prevents restoration.'};
function setup({blockedReason=null,fail=false}={}){let attempts=0;const request=vi.fn(async(url,o)=>{if(url.endsWith('/apply')&&fail&&++attempts===1)throw Error('network');const data=url.endsWith('/apply')?{leagueId,action:o.body.action,recoveryVerified:true}:url.endsWith('/preview')?{leagueId,action:o.body.action,manifest,recoveryVerified:true,confirmation:(o.body.action==='reset'?'RESET':'RESTORE')+' Test League',previewHash:'a'.repeat(64)}:{leagueId,league:{name:'Test League'},blockedReason,archives:[{id:archiveId,at:0,actorName:'Commissioner',restored:false}]};o.validateData(data);return {data};});render(<QueryClientProvider client={new QueryClient()}><SessionContext.Provider value={{httpClient:{request}}}><GuidedLeagueResetControls leagueId={leagueId}/></SessionContext.Provider></QueryClientProvider>);return {request,user:userEvent.setup()};}
it('requires a reviewed manifest and exact league phrase, and safely retries an uncertain save',async()=>{const {request,user}=setup({fail:true});expect(request).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Restart preseason setup'}));await user.type(await screen.findByLabelText('Reason for reset or restore'),'Restart the preseason');await user.click(screen.getByRole('button',{name:'Preview preseason reset'}));await screen.findByText('Candidate Cards');const confirm=screen.getByRole('button',{name:'Confirm preseason reset'});expect(confirm).toBeDisabled();await user.type(screen.getByLabelText('Type RESET Test League to confirm'),'RESET Test League');await user.click(confirm);await screen.findByRole('alert');await user.click(confirm);await screen.findByText('League returned to setup. Choose new dates before starting again.');const writes=request.mock.calls.filter(([url])=>url.endsWith('/apply'));expect(writes).toHaveLength(2);expect(writes[0][1].body).toEqual(writes[1][1].body);expect(writes[0][1].idempotencyKey).toBe(writes[1][1].idempotencyKey);});
it('shows reset restrictions while allowing deliberate recovery archive review',async()=>{const {request,user}=setup({blockedReason:'Pause the league before resetting.'});await user.click(screen.getByRole('button',{name:'Restart preseason setup'}));await screen.findByText('Pause the league before resetting.');await user.type(screen.getByLabelText('Reason for reset or restore'),'Restore original preseason');expect(screen.getByRole('button',{name:'Preview preseason reset'})).toBeDisabled();await user.selectOptions(screen.getByLabelText('Recovery archive'),archiveId);await user.click(screen.getByRole('button',{name:'Preview archive restore'}));await screen.findByText('Restore Test League');expect(request.mock.calls.filter(([url])=>url.endsWith('/apply'))).toHaveLength(0);await user.type(screen.getByLabelText('Type RESTORE Test League to confirm'),'RESTORE Test League');await user.click(screen.getByRole('button',{name:'Confirm archive restore'}));await screen.findByText('League restored. Competition remains paused for review.');});
