import {render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {it,expect,vi} from 'vitest';
import {SessionContext} from '../session/sessionContext.js';
import {SeasonRolloverPreview} from './SeasonRolloverPreview.jsx';
const leagueId='11111111-1111-4111-8111-111111111111';
const data={leagueId,readOnly:true,projectionAvailable:true,source:{label:'2026'},target:{label:'2027'},archived:{weeks:24,results:48},issues:['NEXT_CALENDAR_UNSET'],drafts:[],bindings:[],picks:[{id:'pick',round:2,position:1,originalTeamName:'Ice Owls',ownerTeamName:'Harbour Seals',status:'unused'}],
 contracts:[{id:'contract',playerName:'Casey Skater',teamName:'Ice Owls',currentYears:1,nextYears:0,aavCents:250,outcome:'expire'}],obligations:[{id:'obligation',kind:'buyout',playerName:'Riley Skater',teamName:'Ice Owls',currentAmountCents:100,nextAmountCents:0,outcome:'complete'}],
 summary:{contractsContinuing:0,contractsExpiring:1,playersCarried:0,playersReleased:1,obligationsContinuing:0,obligationsCompleting:1,tradesCancelled:0}};
function setup(value=data){const request=vi.fn(async(url,options)=>{options.validateData(value);return {data:value};});render(<MemoryRouter><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><SessionContext.Provider value={{status:'authenticated',httpClient:{request}}}><SeasonRolloverPreview leagueId={leagueId}/></SessionContext.Provider></QueryClientProvider></MemoryRouter>);return {user:userEvent.setup(),request};}
it('previews preserved history, expiring contracts and traded picks with reads only',async()=>{const {user,request}=setup();expect(request).not.toHaveBeenCalled();await user.click(screen.getByText('Preview next season'));await screen.findByText('2026 → 2027');expect(screen.getByText(/24 matchup weeks and 48 recorded results/)).toBeInTheDocument();await user.click(screen.getByText('Contract changes (1)'));expect(screen.getByText('Casey Skater')).toBeInTheDocument();expect(screen.getByText('Expires')).toBeInTheDocument();await user.click(screen.getByText('Next-season draft picks (1)'));expect(screen.getByText('Harbour Seals')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Refresh season preview'}));expect(request.mock.calls.every(([,o])=>!o.method&&!o.body)).toBe(true);});
it('shows missing preparation without offering a rollover action',async()=>{const {user}=setup({...data,projectionAvailable:false,summary:null,target:null,contracts:[],obligations:[],issues:['NEXT_SEASON_MISSING']});await user.click(screen.getByText('Preview next season'));await screen.findByText('The next season has not been prepared.');expect(screen.queryByText('Contract changes (0)')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/confirm|advance/i})).not.toBeInTheDocument();});
it('fails closed on another league response',async()=>{const {user}=setup({...data,leagueId:'other'});await user.click(screen.getByText('Preview next season'));await screen.findByRole('alert');expect(screen.queryByText('2026 → 2027')).not.toBeInTheDocument();});
