// src/quotes.js

export const HOCKEY_QUOTES = [
  {
    text: "You miss 100% of the shots you don’t take.",
    author: "Wayne Gretzky",
  },
  {
    text: "The highest compliment that you can pay me is to say that I work hard every day.",
    author: "Wayne Gretzky",
  },
  {
    text: "A good hockey player plays where the puck is. A great hockey player plays where the puck is going to be.",
    author: "Wayne Gretzky",
  },
  {
    text: "Hockey is a unique sport in the sense that you need every guy helping you win the game.",
    author: "Wayne Gretzky",
  },
  {
    text: "I skate to where the puck is going to be, not where it has been.",
    author: "Wayne Gretzky",
  },
  { text: "It’s only a game. Why you have to be mad?", author: "Ilya Bryzgalov" },
  { text: "Pressure is what you feel when you don’t know what you’re doing.", author: "Bobby Orr" },
  { text: "The highest compliment that you can pay me is to say that I work hard every day.", author: "Wayne Gretzky" },
  { text: "You can’t win unless you learn how to lose.", author: "Kareem Abdul-Jabbar" },
  { text: "When you’re going through hell, keep going.", author: "Winston Churchill (locker-room classic)" },
  { text: "The name on the front is a hell of a lot more important than the one on the back.", author: "Herb Brooks" },
  { text: "Hockey is figure skating in a war zone.", author: "Unknown" },
  { text: "I went to a fight and a hockey game broke out.", author: "Rodney Dangerfield" },
  { text: "The puck knows what it’s doing. The trick is to make it do it near their net.", author: "Unknown" },
  { text: "Keep your stick on the ice.", author: "Red Green" },
  { text: "If women don’t find you handsome, they should at least find you handy.", author: "Red Green" },
  { text: "A team is not a group of people who work together. A team is a group of people who trust each other.", author: "Simon Sinek (locker-room staple)" },
  { text: "Good players inspire themselves. Great players inspire others.", author: "Mark Messier" },
  { text: "There are no limits. There are plateaus, but you must not stay there—you must go beyond them.", author: "Bruce Lee" },
  { text: "The only way to prove you’re a good sport is to lose.", author: "Ernie Banks" },
  { text: "Play fast, play physical, and have fun doing it.", author: "Unknown" },
  { text: "Finish every check, even if you think you can’t get there.", author: "Unknown" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Hard work beats talent when talent doesn’t work hard.", author: "Tim Notke" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Success is not owned, it’s rented—and the rent is due every day.", author: "Unknown" },
  { text: "You fuckers, pay attention! Nobody's hit a fuckin thing. You get a 3-1 lead, and now you wanna make plays... Fuck the plays! Pound their fucking D! So in game 7 they got nothing left.", author: "Paul Maurice" },
  { text: "My contract sucks.", author: "Roberto Luongo" },
 { text: "We're not going to whine here, Pittsburgh can whine. Pittsburgh whines enough for the whole league, so theres no room for any other team to whine", author: "John Tortorella" },
  { text: "Thats right! Are you kidding me? I did it! Who do you think you are? I am.", author: "Pete Weber" },
  { text: "Why is it called a 'puck'? Because 'dirty little bastard was taken.", author: "Marty Brodeur" },
  { text: "Watching a shootout is like admitting you watch Survivor or search the internet for porn", author: "Brendan Shanahan" },
  { text: "Was Gretzky sick?", author: "Larry Robinson after winning Player of the Week" },
  { text: "The three important elements are: forecheck, backcheck, and paycheck", author: "Gil Perreault" },
  { text: "Hockey players wear numbers because you can't always identify the body with dental records.", author: "Unknown" },
  { text: "The only way you can check Gretzky is to hit him when he is standing still singing the national anthem", author: "Harry Sinden" },
  { text: "I am score", author: "Evgeni Malkin" },
    { text: "We can't lose on Bobblehead Night!", author: "Keith Yandle" },
  { text: "How would you like a job where, every time you make a mistake, a big red light goes on and 18,000 people boo?", author: "Jaques Plante" },
  { text: "90% of the game is half mental", author: "Tyler Seguin" },
    { text: "They say that nobody is perfect. Then they tell you practice makes perfect. I wish they'd make up their minds", author: "Wilt Chamberlain" },
  { text: "Come after me, I'm a man! I'm 40!", author: "Mike Gundy" },
  { text: "We have a great bunch of outside shooters. Unfortunately, all our games are played indoors", author: "Weldon Drew" },
  { text: "How the hell can I make my team better by practicing?", author: "Allen Iverson" },
  { text: "P-Playoffs? Don't talk about playoffs! You kidding me? Playoffs? I just hope we can win a game", author: "Jim Mora" },
  { text: "We didn't underestimate them. They were a lot better than we thought.", author: "Bobby Robson" },
  { text: "If 100 white men chased a black man in the past, it was called the Ku Klux Klan. Today it's called golf.", author: "Tiger Woods" },
  { text: "Baseball, basketball, weiner dog, short shorts, cigarette. Surfboard, ping pong, rugby ball, weiner dog, skiing down on the beach. Sports!", author: "Viagra Boys"},
{ text: "Will Smith don't gotta cuss in raps to sell records, well I do, so fuck him and fuck you too !!", author: "eminem"},
{ text: "I heard it through the grapevine", author: "Marvin Gaye"},
{text: "Chel?", author: "Crust Nost"},
{text: "Starting on left D, looks like he just woke up and combed his hair with a pork chop, Quinn Hughes!", author: "Chris Tanev"},
{text: "scared love don't make none", author: "slug"},
{text: "i am sofa king we todd ed", author: "mf doom"},
{text: "i wish paul maurice was my dad", author: "unknown"},
{text: "what's your second favourite song?", author: "not graeme, ever"},


];
